# build sra-toolkit 2.8.2-1 and requirements
FROM python:3.8.3-slim-buster AS sratoolkit_build

RUN apt-get update && \
    apt-get install -y curl && \
    curl --output sratoolkit.tar.gz https://ftp-trace.ncbi.nlm.nih.gov/sra/sdk/2.8.2-1/sratoolkit.2.8.2-1-ubuntu64.tar.gz && \
    tar xf sratoolkit.tar.gz

# Prepare the worker container
FROM python:3.8.3-slim-buster

RUN groupadd user && \
    useradd --create-home --home-dir /home/user -g user -s /bin/bash user

WORKDIR /home/user

ADD Pipfile Pipfile.lock ./

RUN apt-get update && \
    apt-get install -y libpq-dev build-essential libcurl4-openssl-dev libssl-dev curl && \
    pip install pipenv && \
    pipenv install --system --deploy && \
    pip install sourmash==3.3.0 && \
    apt-get remove -y libpq-dev curl build-essential libssl-dev && \
    apt-get autoremove -y

RUN mkdir -p /home/user/bin
COPY --from=sratoolkit_build sratoolkit.2.8.2-1-ubuntu64/bin/fastq-dump /home/user/bin/fastq-dump

ENV PATH $PATH:/home/user/bin/

USER user

# Configure sra-toolkit to disable cache
RUN mkdir .ncbi
RUN echo '/repository/user/cache-disabled = "true"' > .ncbi/user-settings.mkfg

COPY wort wort
COPY config config

CMD celery -A wort.blueprints.compute.tasks --without-gossip --without-mingle --without-heartbeat -l INFO -c 1 worker
