[project]
name = "wort"
version = "0.1.0"
description = "Add a short description here"
authors = ["Luiz Irber <contact+github@luizirber.org>"]
channels = ["conda-forge", "bioconda"]
platforms = ["linux-64", "linux-aarch64"]

[tasks]

[dependencies]
sourmash-minimal = ">=4.8.5,<4.9"
curl = ">=8.5.0,<8.6"
python = "3.10.*"
biopython = ">=1.81,<2"
pycurl = ">=7.45.1,<7.46"
cachelib = ">=0.10.2,<0.11"
pandas = ">=2.0.3,<2.1"
psycopg2-binary = ">=2.9.9,<2.10"

[target.linux-64.dependencies]
sra-tools = ">=3.0.9,<3.1"

[pypi-dependencies]
flask = "<2.3.0"
gunicorn = ">=20.1.0,<20.2"
redis = ">=4.5.5,<4.6"
boto3 = ">=1.26.155,<1.27"
flask-wtf = ">=1.1.1,<1.2"
flask-migrate = ">=4.0.4,<4.1"
flask-login = ">=0.6.2,<0.7"
jsonschema = ">=4.17.3,<4.18"
flask-shell-ipython = ">=0.5.1,<0.6"
openapi-spec-validator = ">=0.5.7,<0.6"
sentry-sdk = { version = ">=1.39.1,<1.40", extras = ["flask", "celery", "sqlalchemy"] }
connexion = { version = ">=2.14.2,<2.15", extras = ["swagger-ui"] }
celery = { version = ">=5.3.1,<5.4", extras = ["sqs", "s3"] }
