"""tasks

Revision ID: 350a33097a70
Revises: b0738f3203a8
Create Date: 2018-03-01 01:02:35.306454

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "350a33097a70"
down_revision = "b0738f3203a8"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "task",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("name", sa.String(length=128), nullable=True),
        sa.Column("user_id", sa.Integer(), nullable=True),
        sa.Column("complete", sa.Boolean(), nullable=True),
        sa.ForeignKeyConstraint(["user_id"], ["user.id"]),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_task_name"), "task", ["name"], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_task_name"), table_name="task")
    op.drop_table("task")
    # ### end Alembic commands ###
