swagger: '2.0'

basePath: '/'

info:
  title: wort
  version: 0.0.1
  description: https://github.com/dib-lab/wort
  contact:
    name: Luiz Irber
    email: wort@luizirber.org
  license:
    name: BSD 3-Clause
    url: https://raw.githubusercontent.com/dib-lab/wort/master/LICENSE

schemes:
  - https
  - http

consumes:
  - application/json

produces:
  - application/json

paths:
  '/compute/sra/{sra_id}':
    post:
      summary: Request to compute a new signature from an SRA dataset
      operationId: wort.api.compute_sra
      parameters:
        - $ref: '#/parameters/sra_id'
      responses:
        202:
          description: Compute task accepted
  '/view/{public_db}/{dataset_id}':
    get:
      summary: Return a signature
      operationId: wort.api.view_s3
      parameters:
        - $ref: '#/parameters/public_db'
        - $ref: '#/parameters/dataset_id'
      responses:
        200:
          description: Signature
        404:
          description: Database not supported

parameters:
  sra_id:
    name: sra_id
    description: SRA ID for a dataset
    in: path
    required: true
    type: string
    pattern: "\\w{3}\\d{6}"

  public_db:
    name: public_db
    description: Public database
    in: path
    required: true
    type: string
    pattern: "sra|img"

  dataset_id:
    name: dataset_id
    description: ID for a dataset in a public database
    in: path
    required: true
    type: string
